language: ruby
cache: bundler


# Travis will build the site from gh-pages branch
# and deploy the content to master branch
# use gh-pages branch to serve for github pages
# master branch will be used for deployment

branches:
  only:
  - gh-pages
  script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site


